"""
Build a VQA-as-retrieval expansion dataset (local or API caption generation).

For each VQA sample, call an OpenAI-compatible chat API (SiliconFlow) to turn the
(question, answer) pair into a single grammatical, natural-English declarative
caption that describes the image. No templates, no placeholders, no regex -- the
LLM emits the final caption directly.

Output JSON (one entry per sample), written to
    outputs/vqa_expansions/{split}_{tag}_expansions.json
    [
      {
        "imagefilename": "000000397899.jpg",
        "imagepath": "TrainDatasets/mscoco_captions/images/000000397899.jpg",
        "type": 0,
        "question": "...",
        "answer": "...",
        "caption": "<declarative English sentence>"
      },
      ...
    ]

{tag} is a tag identifying the model (e.g. 'gemma', 'llama'); each model writes
its own {split}_{tag}_captions.jsonl / _expansions.jsonl / .json so captions
from different models never collide.

Resumable: streams entries to a .jsonl (one per line), caches generated captions
to {split}_{tag}_captions.jsonl (keyed by question+answer, so identical Q/A
pairs across images reuse one generation), and consolidates to the final
{split}_{tag}_expansions.json array at the end.

    # LOCAL backend (default): transformers. Two families, paths from config.py:
    #   gemma -> AutoProcessor + AutoModelForMultimodalLM
    #   llama -> AutoTokenizer  + AutoModelForCausalLM
    # quick local dry run (3 samples, start fresh), one-at-a-time for debugging
    # tune throughput / precision / explicit path

    # API backend (original HTTP path): provider/model aliases in the api config file

Local backend settings all have CLI overrides:
--backend --model-kind --model-path --batch-size --dtype --device --no-batch.
The dedup cache ({split}_captions.jsonl) and resume logic are shared by both
backends, so captions already generated by either are reused.

API credentials live in the api config file (gitignored; an example template ships alongside it). Add more providers or models there -- select them with --provider/--model.
"""

import argparse
import json
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List, Tuple

import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config
from utils.logger import get_logger, log_exception

logger = get_logger("build_vqa_expansions", config.LOG_DIR / "build_vqa_expansions.log")

TYPE_NAMES = {0: "object", 1: "number", 2: "color", 3: "location"}

DEFAULT_PROVIDER = "siliconflow"
DEFAULT_MODEL_ALIAS = "deepseek-v4-pro"

_SPLIT_FILES = {
    "train": {
        "questions": "questions", "img_filenames": "img_filenames",
        "types": "types", "answers": "answers",
    },
    "test": {
        "questions": "questions_filtered", "img_filenames": "img_filenames_filtered",
        "types": "types_filtered", "answers": "answers_filtered",
    },
}


# =============================================================================
# Data loading
# =============================================================================
def load_split(split: str) -> List[Tuple[str, int, str, str]]:
    """Return [(filename, type, question, answer), ...] line-aligned."""
    base = config.VQA_TRAIN_QUESTIONS.parent.parent  # .../mscoco_captions
    split_dir = base / split
    names = _SPLIT_FILES[split]
    paths = {k: split_dir / f"{v}.txt" for k, v in names.items()}
    for k, p in paths.items():
        if not p.exists():
            raise FileNotFoundError(f"Missing {k} file: {p}")

    def read(p: Path) -> List[str]:
        return [line.rstrip("\n") for line in p.read_text(encoding="utf-8").splitlines()]

    questions = read(paths["questions"])
    filenames = read(paths["img_filenames"])
    types = read(paths["types"])
    answers = read(paths["answers"])
    n = len(questions)
    if not (len(filenames) == len(types) == len(answers) == n):
        raise ValueError(f"Line mismatch in {split}: q={n} f={len(filenames)} "
                         f"t={len(types)} a={len(answers)}")
    samples = []
    for fn, t, q, a in zip(filenames, types, questions, answers):
        t = int(t.strip()) if t.strip() else 0
        samples.append((fn.strip(), t, q.strip(), a.strip()))
    logger.info(f"Loaded {len(samples)} samples from split={split}")
    return samples


def image_relpath(filename: str) -> str:
    """Relative-to-project-root image path (forward slashes), e.g.
    'TrainDatasets/mscoco_captions/images/000000397899.jpg'."""
    full = config.VQA_IMAGES_DIR / filename
    try:
        return str(full.relative_to(config.PROJECT_ROOT)).replace("\\", "/")
    except ValueError:
        return str(full).replace("\\", "/")


# =============================================================================
# Caption generator (API-only, OpenAI-compatible via urllib)
# =============================================================================
_CAPTION_SYSTEM = (
    "You convert visual question-answer pairs into natural English declarative "
    "image-description sentences. Always output English. Every sentence MUST be "
    "grammatically correct and read like a fluent caption of what the image shows."
)

_CAPTION_USER = """Rewrite the following question-answer pair as ONE declarative sentence that DESCRIBES THE IMAGE. The answer must appear naturally inside the sentence.

Question: {QUESTION}
Answer: {ANSWER}
Answer type: {TYPE}   (one of: color | number | location | object)

Rules:
- Output ONLY the caption sentence. No quotes, no explanation, no extra text.
- Make it declarative and image-descriptive, not a question.
- GRAMMAR (important): the sentence MUST be grammatically correct, natural English. Fix word order, subject-verb agreement, articles (a/an/the), pluralization, and prepositions. You MAY reorder or lightly rephrase the question's words to achieve fluent grammar. Drop a leading "a"/"an" when the subject is plural (e.g. "carrots are ...", not "a carrots are ..."). For "how many" questions, prefer "there are <answer> ...".

Examples:
Q: what is the man holding a snowboard on top of a snow covered | A: hill | type: object
a man is holding a snowboard on top of a snow covered hill

Q: what are sitting on the counter in different stages of cutting with a knife | A: carrots | type: object
carrots are sitting on the counter in different stages of cutting with a knife

Q: what is the color of the bus | A: green | type: color
the color of the bus is green

Q: how many red motorcycles with riders in protective gear are on the street | A: three | type: number
there are three red motorcycles with riders in protective gear on the street

Q: where is the woman while her baby is sleeping | A: kitchen | type: location
the woman is in the kitchen while her baby is sleeping

Now convert:
Q: {QUESTION} | A: {ANSWER} | type: {TYPE}"""


class CaptionGenerator:
    """Call an OpenAI-compatible chat API to emit a final caption directly."""

    def __init__(self, api_key: str, base_url: str, model: str,
                 max_retries: int = 5, retry_wait: float = 5.0,
                 delay: float = 0.5, timeout: int = 60, max_tokens: int = 96):
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.max_retries = max_retries
        self.retry_wait = retry_wait
        self.delay = delay
        self.timeout = timeout
        self.max_tokens = max_tokens

    def _chat(self, messages: List[Dict]) -> str:
        url = self.base_url + "/chat/completions"
        body = json.dumps({
            "model": self.model,
            "messages": messages,
            "temperature": 0,
            "max_tokens": self.max_tokens,
        }).encode("utf-8")
        last_err = None
        for attempt in range(self.max_retries):
            try:
                req = urllib.request.Request(
                    url, data=body,
                    headers={"Authorization": f"Bearer {self.api_key}",
                             "Content-Type": "application/json"},
                    method="POST",
                )
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    data = json.loads(resp.read().decode("utf-8"))
                return data["choices"][0]["message"]["content"].strip()
            except (urllib.error.URLError, urllib.error.HTTPError, OSError, KeyError, ValueError) as e:
                last_err = e
                wait = self.retry_wait * (attempt + 1)
                logger.warning(f"API call failed (attempt {attempt + 1}/{self.max_retries}): {e}; retry in {wait}s")
                time.sleep(wait)
        raise RuntimeError(f"API call failed after {self.max_retries} attempts: {last_err}")

    def generate(self, question: str, answer: str, qtype: int) -> str:
        # Use .replace (not .format) so any literal braces survive untouched.
        user = (_CAPTION_USER
                .replace("{QUESTION}", question)
                .replace("{ANSWER}", answer)
                .replace("{TYPE}", TYPE_NAMES.get(qtype, "object")))
        messages = [
            {"role": "system", "content": _CAPTION_SYSTEM},
            {"role": "user", "content": user},
        ]
        text = self._chat(messages)
        if self.delay:
            time.sleep(self.delay)
        # Keep only the last non-empty line (model may add a stray preamble); strip quotes.
        cand = [c.strip().strip('"').strip("'").strip() for c in text.splitlines() if c.strip()]
        caption = cand[-1] if cand else ""
        if not caption:
            logger.warning(f"Empty caption for Q={question!r} A={answer!r}; using answer as caption")
            caption = answer
        return caption


class LocalCaptionGenerator:
    """Generate captions with a local Hugging Face model loaded via transformers.

    Two model families, selected by `kind`:
      - "gemma": AutoProcessor + AutoModelForMultimodalLM (text-only generation)
      - "llama": AutoTokenizer  + AutoModelForCausalLM

    Loads model + (processor|tokenizer) ONCE. Reuses the SAME prompt templates and
    output post-processing as the API CaptionGenerator, so backends are
    interchangeable. Batched generation (left-padded) drives throughput via
    generate_batch(); generate()/generate_one() keep a single-sample path.
    """

    supports_batch = True
    # kind -> (processor class name, model class name) on the `transformers` module.
    _KIND_CLASSES = {
        "gemma": ("AutoProcessor", "AutoModelForMultimodalLM"),
        "llama": ("AutoTokenizer", "AutoModelForCausalLM"),
    }

    def __init__(self, kind: str = "gemma", model_path: str = "", dtype: str = "bf16",
                 device: str = "cuda", batch_size: int = 32, max_new_tokens: int = 96,
                 do_sample: bool = False, trust_remote_code: bool = False,
                 model_name: str = ""):
        import torch
        import transformers

        if kind not in self._KIND_CLASSES:
            raise ValueError(f"Unknown model kind {kind!r}; use 'gemma' or 'llama'.")
        if not model_path:
            raise ValueError("Local backend requires a model path: set "
                             "LLM_LOCAL_GEMMA_PATH/LLM_LOCAL_LLAMA_PATH in config.py "
                             "or pass --model-path.")
        model_dir = Path(model_path).expanduser()
        if not model_dir.exists():
            raise FileNotFoundError(f"Local model path not found: {model_dir}")

        dtype_map = {"bf16": torch.bfloat16, "fp16": torch.float16, "fp32": torch.float32}
        if dtype not in dtype_map:
            raise ValueError(f"dtype must be one of {list(dtype_map)}, got {dtype!r}")
        torch_dtype = dtype_map[dtype]

        # transformers 5.x renamed the from_pretrained kwarg torch_dtype -> dtype.
        major = int(transformers.__version__.split(".")[0])
        dtype_kw = "dtype" if major >= 5 else "torch_dtype"

        resolved_device = device
        if device == "auto":
            resolved_device = "cuda" if torch.cuda.is_available() else "cpu"

        self.kind = kind
        self.torch = torch
        self.batch_size = batch_size
        self.max_new_tokens = max_new_tokens
        self.do_sample = do_sample
        self.device = resolved_device
        self.model_name = model_name or model_dir.name

        logger.info(f"Loading local model [{kind}]: {model_dir} (dtype={dtype}, "
                    f"device={resolved_device}, batch={batch_size}, do_sample={do_sample})")
        self._load(model_dir, dtype_kw, torch_dtype, trust_remote_code, device)

        # Inner token-level handle (pad token, padding side, pad_token_id).
        # AutoTokenizer has no .tokenizer attr; AutoProcessor does.
        self.tokenizer = getattr(self.processor, "tokenizer", self.processor)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        # Left padding so every prompt ends at the same position for generation.
        self.tokenizer.padding_side = "left"

        if device != "auto":
            self.model = self.model.to(resolved_device)
        self.model.eval()
        logger.info(f"Local model ready: {self.model_name} ({kind}) on {resolved_device}")

    def _load(self, model_dir: Path, dtype_kw: str, torch_dtype, trust_remote_code: bool,
              device: str):
        """Load processor/tokenizer + model for the configured family."""
        import transformers
        proc_name, model_name = self._KIND_CLASSES[self.kind]
        proc_cls = getattr(transformers, proc_name)
        model_cls = getattr(transformers, model_name)
        self.processor = proc_cls.from_pretrained(
            str(model_dir), trust_remote_code=trust_remote_code)
        load_kwargs = {dtype_kw: torch_dtype, "trust_remote_code": trust_remote_code}
        if device == "auto":
            load_kwargs["device_map"] = "auto"   # requires accelerate
        self.model = model_cls.from_pretrained(str(model_dir), **load_kwargs)

    # -- prompt building ----
    def _messages(self, question: str, answer: str, qtype: int) -> List[Dict]:
        user = (_CAPTION_USER
                .replace("{QUESTION}", question)
                .replace("{ANSWER}", answer)
                .replace("{TYPE}", TYPE_NAMES.get(qtype, "object")))
        return [{"role": "system", "content": _CAPTION_SYSTEM},
                {"role": "user", "content": user}]

    def _raw_prompt(self, question: str, answer: str, qtype: int) -> str:
        msgs = self._messages(question, answer, qtype)
        return f"{msgs[0]['content']}\n\n{msgs[1]['content']}"

    def _to_prompt(self, question: str, answer: str, qtype: int) -> str:
        """Render the prompt for this model family.

        - gemma: the Gemma4Unified processor/tokenizer ships NO chat template and
          emits EOS immediately on a bare prompt, so wrap it in Gemma turn markers
          (`<start_of_turn>user ... <end_of_turn>\\n<start_of_turn>model\\n`).
        - llama: apply the chat template; fall back to a plain string for base
          models that ship no template.
        """
        raw = self._raw_prompt(question, answer, qtype)
        if self.kind == "gemma":
            return f"<start_of_turn>user\n{raw}<end_of_turn>\n<start_of_turn>model\n"
        try:
            return self.processor.apply_chat_template(
                self._messages(question, answer, qtype),
                tokenize=False, add_generation_prompt=True)
        except Exception:
            return raw

    @staticmethod
    def _decode_caption(text: str) -> str:
        # Keep only the last non-empty line; strip surrounding quotes (same as API).
        cand = [c.strip().strip('"').strip("'").strip()
                for c in text.splitlines() if c.strip()]
        return cand[-1] if cand else ""

    def _extract_caption(self, text: str) -> str:
        """Pull the caption out of the model's raw output.

        Local models emit the caption first, then often keep going (Gemma
        hallucinates another turn; a base Llama generates more few-shot examples).
        Cut Gemma at its turn marker, then take the FIRST non-empty line. Reject
        lines that look like hallucinated few-shot example headers ('Q: ...' or
        '... | A: ... | type: ...') so a base model degrades to the answer rather
        than emitting garbage.
        """
        if self.kind == "gemma":
            text = text.split("<end_of_turn>")[0]
        cand = [c.strip().strip('"').strip("'").strip()
                for c in text.splitlines() if c.strip()]
        cap = cand[0] if cand else ""
        low = cap.lower()
        if low[:2] == "q:" or " | a:" in low or "| type:" in low:
            return ""
        return cap

    def generate(self, question: str, answer: str, qtype: int) -> str:
        """Single-sample interface shared with the API CaptionGenerator."""
        return self.generate_one(question, answer, qtype)

    def generate_one(self, question: str, answer: str, qtype: int) -> str:
        return self.generate_batch([(question, answer, qtype)])[0]

    def generate_batch(self, items: List[Tuple[str, str, int]]) -> List[str]:
        """One forward pass over `items`. The caller chunks by self.batch_size.

        items: list of (question, answer, qtype). Returns one caption per item.
        """
        torch = self.torch
        prompts = [self._to_prompt(q, a, t) for q, a, t in items]
        enc = self._encode(prompts)
        input_len = enc["input_ids"].shape[1]
        enc = {k: v.to(self.device) for k, v in enc.items()}
        gen_kwargs = dict(max_new_tokens=self.max_new_tokens,
                          do_sample=self.do_sample,
                          pad_token_id=self.tokenizer.pad_token_id)
        if self.kind == "gemma":
            # Stop at the turn marker so Gemma doesn't keep generating another turn.
            gen_kwargs["stop_strings"] = ["<end_of_turn>"]
            gen_kwargs["tokenizer"] = self.tokenizer
        with torch.no_grad():
            out = self.model.generate(**enc, **gen_kwargs)
        gen = out[:, input_len:]                      # drop the padded prompt
        texts = self._batch_decode(gen)
        captions = [self._extract_caption(t) for t in texts]
        # Fall back to the answer if the model emitted nothing usable.
        return [c if c else a for c, (_, a, _) in zip(captions, items)]

    # -- tokenization + decoding --------------------------------------------
    def _encode(self, prompts: List[str]) -> Dict:
        """Tokenize a batch of prompts. AutoProcessor wants text= (and may reject
        a plain list); AutoTokenizer takes a positional list. If the Gemma
        processor refuses a text-only batch, fall back to its inner tokenizer."""
        if self.kind == "gemma":
            try:
                return self.processor(text=prompts, return_tensors="pt",
                                      padding=True, truncation=True)
            except Exception as e:
                logger.warning(f"Gemma processor text-encode failed ({e}); "
                               f"falling back to its tokenizer")
        return self.tokenizer(prompts, return_tensors="pt", padding=True, truncation=True)

    def _batch_decode(self, token_ids) -> List[str]:
        fn = getattr(self.processor, "batch_decode", None) or self.tokenizer.batch_decode
        return fn(token_ids, skip_special_tokens=True)


def load_api_config(path: Path) -> Dict:
    """Load api_config.json: {provider: {api_key, base_url, models: {alias: id}}}.

    Top-level keys starting with '_' (e.g. '_readme') are ignored, so the file can
    carry documentation. See api_config.example.json for the schema.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"api_config not found: {path}\nCopy api_config.example.json to "
            f"{path.name} and fill in your key (it is gitignored).")
    return json.loads(path.read_text(encoding="utf-8"))


def resolve_provider(cfg: Dict, provider: str) -> Dict:
    """Return the provider block for `provider`."""
    available = [k for k in cfg if not k.startswith("_") and isinstance(cfg[k], dict)]
    prov = cfg.get(provider)
    if not isinstance(prov, dict):
        raise ValueError(f"Provider '{provider}' not in api_config. Available: {available}")
    if not prov.get("api_key") or not prov.get("base_url"):
        raise ValueError(f"Provider '{provider}' must define 'api_key' and 'base_url'")
    return prov


def make_api_generator(args) -> CaptionGenerator:
    cfg = load_api_config(Path(args.api_config))
    prov = resolve_provider(cfg, args.provider)
    models = prov.get("models") or {}
    model_id = models.get(args.model)
    if model_id is None:
        # Treat --model as a raw model id if it is not a known alias.
        model_id = args.model
        logger.warning(f"Model alias '{args.model}' not in provider '{args.provider}' "
                       f"models map (have {list(models)}); using it as a raw model id")
    logger.info(f"Using API caption generator: provider={args.provider} "
                f"model={args.model} ({model_id}) base_url={prov['base_url']}")
    return CaptionGenerator(
        api_key=prov["api_key"], base_url=prov["base_url"], model=model_id,
        max_retries=config.LLM_API_MAX_RETRIES, retry_wait=config.LLM_API_RETRY_WAIT,
        delay=config.LLM_API_DELAY, timeout=config.LLM_API_TIMEOUT,
    )


def make_local_generator(args) -> "LocalCaptionGenerator":
    kind = args.model_kind or config.LLM_LOCAL_MODEL_KIND
    default_path = {"gemma": config.LLM_LOCAL_GEMMA_PATH,
                    "llama": config.LLM_LOCAL_LLAMA_PATH}.get(kind, "")
    model_path = args.model_path or config.LLM_LOCAL_MODEL_PATH or default_path
    dtype = args.dtype or config.LLM_LOCAL_DTYPE
    device = args.device or config.LLM_LOCAL_DEVICE
    return LocalCaptionGenerator(
        kind=kind,
        model_path=model_path,
        dtype=dtype,
        device=device,
        batch_size=args.batch_size,
        max_new_tokens=config.LLM_LOCAL_MAX_NEW_TOKENS,
        do_sample=config.LLM_LOCAL_DO_SAMPLE,
        trust_remote_code=config.LLM_LOCAL_TRUST_REMOTE_CODE,
        model_name=config.LLM_LOCAL_MODEL_NAME,
    )


def make_generator(args):
    """Dispatch to the local (transformers) or api (HTTP) backend."""
    backend = args.backend
    if backend == "local":
        return make_local_generator(args)
    if backend == "api":
        return make_api_generator(args)
    raise ValueError(f"Unknown --backend {backend!r}; use 'local' or 'api'.")


# =============================================================================
# Pipeline
# =============================================================================
def caption_cache_key(question: str, answer: str) -> str:
    return f"{question}\t{answer}"


def build_entry(filename: str, qtype: int, question: str, answer: str, caption: str) -> Dict:
    return {
        "imagefilename": filename,
        "imagepath": image_relpath(filename),
        "type": qtype,
        "question": question,
        "answer": answer,
        "caption": caption,
    }


def _fs_safe(name: str) -> str:
    """Filesystem-safe token: keep alnum / '-' / '.' / '_', replace the rest."""
    return "".join(c if (c.isalnum() or c in "-_.") else "_" for c in name) or "model"


def derive_model_tag(generator) -> str:
    """Short tag identifying the model, used in output filenames:
        {split}_{tag}_captions.jsonl
        {split}_{tag}_expansions.jsonl / .json

    Local backend -> the model dir basename (e.g. 'gemma' / 'llama').
    API backend   -> the resolved model id (sanitized).
    Different models get separate files because they emit different captions for
    the same (question, answer) pair.
    """
    name = getattr(generator, "model_name", "") or getattr(generator, "model", "") or "model"
    return _fs_safe(name)


def load_caption_cache(path: Path) -> Dict[str, str]:
    """Return {question+answer -> caption} cache."""
    cache: Dict[str, str] = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
                cache[rec["key"]] = rec["caption"]
            except (json.JSONDecodeError, KeyError):
                continue
    return cache


def count_lines(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())


def consolidate(jsonl_path: Path, json_path: Path) -> int:
    entries = []
    for line in jsonl_path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            entries.append(json.loads(line))
    json_path.write_text(json.dumps(entries, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(entries)


def parse_args():
    p = argparse.ArgumentParser(description="Build VQA expansion dataset (local or API caption generation)")
    p.add_argument("--split", type=str, default="test", choices=["train", "test", "both"])
    # -- backend selection -----------------------------------------------------
    p.add_argument("--backend", type=str, default=config.LLM_BACKEND,
                   choices=["local", "api"],
                   help="Caption backend: 'local' (transformers, default) or 'api' (HTTP).")
    p.add_argument("--model-kind", type=str, default=None, choices=["gemma", "llama"],
                   help="Local model family: 'gemma' (default; AutoProcessor + "
                        "AutoModelForMultimodalLM) or 'llama' (AutoTokenizer + "
                        "AutoModelForCausalLM). Default: config.LLM_LOCAL_MODEL_KIND.")
    p.add_argument("--model-path", type=str, default=None,
                   help="Local model dir; overrides the kind's config path "
                        "(LLM_LOCAL_GEMMA_PATH / LLM_LOCAL_LLAMA_PATH).")
    p.add_argument("--batch-size", type=int, default=config.LLM_LOCAL_BATCH_SIZE,
                   help="Captions per forward pass in batched mode (default: %(default)s).")
    p.add_argument("--dtype", type=str, default=None, choices=["bf16", "fp16", "fp32"],
                   help="Model dtype for --backend local (default: config.LLM_LOCAL_DTYPE).")
    p.add_argument("--device", type=str, default=None,
                   help="Device for --backend local: cuda / cuda:0 / cpu / auto "
                        "(default: config.LLM_LOCAL_DEVICE).")
    p.add_argument("--no-batch", action="store_true",
                   help="Disable batching; generate one caption at a time (debug; much slower).")
    # -- API-only (--backend api) ----------------------------------------------
    p.add_argument("--provider", type=str, default=DEFAULT_PROVIDER,
                   help="Provider key in api_config.json (e.g. siliconflow)")
    p.add_argument("--model", type=str, default=DEFAULT_MODEL_ALIAS,
                   help="Model alias under the provider's 'models' map (or a raw model id)")
    p.add_argument("--api-config", type=str, default=str(config.API_CONFIG_PATH),
                   help="Path to api_config.json")
    p.add_argument("--limit", type=int, default=20,
                   help="Samples to process this run (0 = all). Default 20 (dry-run safety).")
    p.add_argument("--output-dir", type=str, default=None)
    p.add_argument("--no-resume", action="store_true",
                   help="Start from scratch (overwrite existing outputs for the split)")
    return p.parse_args()


def run_split(split: str, args, generator, out_dir: Path) -> Path:
    samples = load_split(split)
    tag = derive_model_tag(generator)
    cap_path = out_dir / f"{split}_{tag}_captions.jsonl"   # per-model dedup cache
    exp_jsonl = out_dir / f"{split}_{tag}_expansions.jsonl"
    exp_json = out_dir / f"{split}_{tag}_expansions.json"
    logger.info(f"[{split}] model tag: {tag}")

    if args.no_resume:
        for p in (cap_path, exp_jsonl, exp_json):
            if p.exists():
                p.unlink()

    cache = load_caption_cache(cap_path)
    done = count_lines(exp_jsonl)
    logger.info(f"[{split}] resume: {done} entries already written, "
                f"{len(cache)} captions cached")

    total = len(samples)
    limit = args.limit if (args.limit and args.limit > 0) else total
    end = min(total, done + limit)  # process [done, end)
    logger.info(f"[{split}] processing samples [{done}, {end}) of {total} "
                f"(--limit {args.limit})")

    use_batch = getattr(generator, "supports_batch", False) and not args.no_batch
    if use_batch:
        logger.info(f"[{split}] using BATCHED local generation (batch_size={args.batch_size})")
        _run_batched(split, samples, done, end, generator, args.batch_size,
                     cache, cap_path, exp_jsonl)
    else:
        logger.info(f"[{split}] using single-sample generation")
        _run_single(split, samples, done, end, generator, cache, cap_path, exp_jsonl)

    n = consolidate(exp_jsonl, exp_json)
    logger.info(f"[{split}] consolidated {n} entries -> {exp_json}")
    return exp_json


def _run_single(split, samples, done, end, generator, cache, cap_path, exp_jsonl):
    """One-at-a-time path: API backend, or local with --no-batch."""
    with open(cap_path, "a", encoding="utf-8") as cf, \
         open(exp_jsonl, "a", encoding="utf-8") as ef:
        for i in range(done, end):
            filename, qtype, question, answer = samples[i]
            key = caption_cache_key(question, answer)
            caption = cache.get(key)
            if caption is None:
                caption = generator.generate(question, answer, qtype)
                cache[key] = caption
                cf.write(json.dumps(
                    {"key": key, "question": question, "answer": answer,
                     "type": qtype, "caption": caption},
                    ensure_ascii=False) + "\n")
                cf.flush()
            entry = build_entry(filename, qtype, question, answer, caption)
            ef.write(json.dumps(entry, ensure_ascii=False) + "\n")
            ef.flush()
            if (i - done + 1) % 1000 == 0:
                logger.info(f"[{split}] {i + 1}/{end} entries written")


def _run_batched(split, samples, done, end, generator, batch_size, cache,
                 cap_path, exp_jsonl):
    """Batched path (local backend): collect unique missing (q,a), generate in
    chunks flushed to the caption cache, then write expansions (all cache hits)."""
    # 1) collect unique keys not yet cached, in first-appearance order
    missing = []          # list of (key, question, answer, qtype)
    seen = set()
    for i in range(done, end):
        _, qtype, question, answer = samples[i]
        key = caption_cache_key(question, answer)
        if key not in cache and key not in seen:
            seen.add(key)
            missing.append((key, question, answer, qtype))
    logger.info(f"[{split}] batched: {len(missing)} new unique (q,a) to generate, "
                f"{(end - done) - len(missing)} served from cache")

    # 2) generate + persist in chunks (flush each chunk -> crash-safe resume)
    if missing:
        total_miss = len(missing)
        with open(cap_path, "a", encoding="utf-8") as cf:
            for start in range(0, total_miss, batch_size):
                chunk = missing[start:start + batch_size]
                captions = generator.generate_batch(
                    [(q, a, t) for _, q, a, t in chunk])
                for (key, question, answer, qtype), caption in zip(chunk, captions):
                    cache[key] = caption
                    cf.write(json.dumps(
                        {"key": key, "question": question, "answer": answer,
                         "type": qtype, "caption": caption},
                        ensure_ascii=False) + "\n")
                cf.flush()
                done_miss = min(start + batch_size, total_miss)
                logger.info(f"[{split}] generated {done_miss}/{total_miss} new captions")

    # 3) write expansions (all cache hits now)
    with open(exp_jsonl, "a", encoding="utf-8") as ef:
        for i in range(done, end):
            filename, qtype, question, answer = samples[i]
            key = caption_cache_key(question, answer)
            caption = cache[key]
            entry = build_entry(filename, qtype, question, answer, caption)
            ef.write(json.dumps(entry, ensure_ascii=False) + "\n")
            ef.flush()
            if (i - done + 1) % 1000 == 0:
                logger.info(f"[{split}] {i + 1}/{end} entries written")


def main():
    args = parse_args()
    out_dir = Path(args.output_dir) if args.output_dir else (config.OUTPUT_DIR / "vqa_expansions")
    out_dir.mkdir(parents=True, exist_ok=True)

    generator = make_generator(args)

    splits = ["train", "test"] if args.split == "both" else [args.split]
    for split in splits:
        run_split(split, args, generator, out_dir)

    logger.info("Done.")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log_exception(logger, e, "build_vqa_expansions failed")
        raise
